[EAS]
userName = "user"
password = "kduser"
slnName = "eas"
dcName = "t190822"
language = "L2"
dbType = 1
authPattern = "BaseDB"
isEncodePwd = 0

[remote_db]
user_name = "mysqluser"
password = "mysqlpasswd"
url = "172.0.0.1"
database_name = "databasename"